[package]
name = "tokentamer"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "tokentamer"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.20.0"
