[package]
name = "triehard"
version = "0.1.0"
edition = "2021"
authors = ["Arthur Book", "https://github.com/ArthurBook"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module"] }

[lib]
crate-type = ["cdylib"]
